import type { Metadata } from "next";
import { M_PLUS_1_Code } from "next/font/google";
import "./globals.css";
import ThemeContextProvider from "@/context/theme-context";
import ThemeSwitch from "@/components/theme-switch";
import Background from "@/components/background";
import Header from "@/components/header";

const font = M_PLUS_1_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "William Lowe | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} min-h-screen text-zinc-900 dark:text-zinc-50/80`}
      >
        <ThemeContextProvider>
          <Background />
          <Header />
          {children}
          <ThemeSwitch />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
